name: E2E Tests

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta el workflow cada hora
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Execute tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test
        env:
          CI: true

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: reports/
